### EXERCISE 1

Create:
1. A three-dimensional NumPy array of zeros
2. A two-dimensional NumPy array of random integer numbers (from a given range)
3. A three-dimensional NumPy array with first 27 prime numbers (you can use a primePy package or just enter them manually)



In [2]:
import numpy as np
# 3d numpy array of zeros
np.zeros((3,3,3))


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [27]:
two_d_array = np.array(np.arange(12.0))
two_d_array = two_d_array.reshape((4,3))
print(two_d_array)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [18]:
from primePy import primes
prime = np.array(primes.first(27))
prime.reshape((3,3,3))

array([[[  2,   3,   5],
        [  7,  11,  13],
        [ 17,  19,  23]],

       [[ 29,  31,  37],
        [ 41,  43,  47],
        [ 53,  59,  61]],

       [[ 67,  71,  73],
        [ 79,  83,  89],
        [ 97, 101, 103]]])

### EXERCISE 2

Write a programme to replace zeros with np.nan values in a given NumPy array


In [31]:
print("---original--- \n",two_d_array)

def replace_zeros(array:np.array):
    replaced = np.copy(array)
    replaced[replaced == 0] = np.nan
    return replaced
print("---replaced--- \n", replace_zeros(two_d_array))

---original--- 
 [[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
---replaced--- 
 [[nan  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


### EXERCISE 3

Create a NumPy array of booleans and illustrate the following methods
1. .any()
2. .all()

Apply these methods for the complete array and by every dimension (e.g., by rows)


In [58]:
booleans = np.array([False,True,True,True,False,False,False,False])
booleans = booleans.reshape((2,2,2))
print(booleans)

[[[False  True]
  [ True  True]]

 [[False False]
  [False False]]]


In [66]:
result = np.any(booleans, axis = 1)
print("-----any()-----\n",result)

result = np.all(booleans, axis = 1)
print("-----all()-----\n",result)

-----any()-----
 [[ True  True]
 [False False]]
-----all()-----
 [[False  True]
 [False False]]


### EXERCISE 4

Create two 4x4 NumPy arrays of random numbers from the range [0,100].
Create a boolean mask from the second array, which is 1 for all value more than 50 and 0 otherwise and use it to filtering the first array (replace elements, where mask is 0, with zetos).

In [79]:
rng_array = np.random.randint(0,100,(4,4))
rng_array

array([[53,  5, 38, 17],
       [79,  4, 42, 58],
       [31,  1, 65, 41],
       [57, 35, 11, 46]])

In [100]:
mask = rng_array[:,:] > 50
masked = rng_array.copy()

masked[mask] = 1
masked[mask == False] = 0
masked


array([[1, 0, 0, 0],
       [1, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 0]])

### EXERCISE 5

Write a  program to compute the mean, median, standard deviation, and variance of a given NumPy array along the second axis and provide several test cases for the programme. Recall the meaning of mentioned statistical characteristics.



In [114]:
def stats_for_a_sample(array:np.array):
    print("Mean of the array along second axis")
    print(np.mean(array,axis=1))
    print("Median of the array along second axis")
    print(np.median(array,axis=1))
    print("Standard deviation of the array along second axis")
    print(np.std(array,axis=1,ddof=1))
    print("Variance of the array along second axis")
    print(np.var(array,axis=1,ddof=1))

In [118]:
"""
-5, 1, 8, 7, 2
mean = 2.6, median = 2 std = 5.224940191, var = 27.3
1,0,-1,1,-1
mean = 0, median = 0, std = 1, var = 1
10, 34, 23, 54, 9
mean = 26, meadian = 23, std = 18.722, variance = 350.500
"""
stat_array = np.array([[-5,1,8,7,2],[1,0,-1,1,-1],[10, 34, 23, 54, 9]])
stat_array

array([[-5,  1,  8,  7,  2],
       [ 1,  0, -1,  1, -1],
       [10, 34, 23, 54,  9]])

In [119]:
stats_for_a_sample(stat_array)

Mean of the array along second axis
[ 2.6  0.  26. ]
Median of the array along second axis
[ 2.  0. 23.]
Standard deviation of the array along second axis
[ 5.22494019  1.         18.72164523]
Variance of the array along second axis
[ 27.3   1.  350.5]


### EXERCISE 6

Write a  program to calculate the difference between the maximum and the minimum values of a given NumPy array along the all available dimensions.

E.g., for a matrix:

[[1, 2, 3]

 [10, 2, 30]
 
 [5, 20, 10]]
 
 
the programme should return:

Axis 0: [9, 18, 27]

Axis 1: [2, 28, 15]


In [129]:
min_max_matrix1 = np.array(
[[1, 2, 3],
[10, 2, 30],
[5, 20, 10]]
)

min_max_matrix2 = np.random.randint(0,100,(3,3,3))

In [130]:
def min_max_along_axis(array:np.array):
    dimensions = array.ndim
    for i in range(dimensions):
        print(f"Axis {i}: {np.max(array,axis=i) - np.min(array,axis=i)}")

In [131]:
min_max_along_axis(min_max_matrix1)
min_max_along_axis(min_max_matrix2)

Axis 0: [ 9 18 27]
Axis 1: [ 2 28 15]
Axis 0: [[24 24 84]
 [40 83 96]
 [43 40 45]]
Axis 1: [[15 70 84]
 [37 60 39]
 [27 70 96]]
Axis 2: [[76 41 48]
 [54 27 21]
 [28 95 59]]


### EXERCISE 7

Create a 7x7 NumPy array of random integers and subset all possible 5x5 sub-arrays (including overlapping ones).

In [13]:
seven = np.random.randint(0,100,(7,7))
seven

array([[91, 33, 42, 83, 89, 54, 57],
       [31, 77, 19, 93, 17, 99, 44],
       [79, 31, 25, 49, 14, 50, 61],
       [40, 42, 88, 27, 96, 61, 52],
       [49, 90, 78, 70, 86, 98, 89],
       [72, 97, 77, 81, 19,  3, 60],
       [71,  5, 80, 36, 58, 79, 13]])

In [23]:
five_sub_arrays = []

for row in range(3):
    for column in range(3):
        five_sub_arrays.append(seven[row:row+5,column:column+5])

In [24]:
five_sub_arrays

[array([[91, 33, 42, 83, 89],
        [31, 77, 19, 93, 17],
        [79, 31, 25, 49, 14],
        [40, 42, 88, 27, 96],
        [49, 90, 78, 70, 86]]),
 array([[33, 42, 83, 89, 54],
        [77, 19, 93, 17, 99],
        [31, 25, 49, 14, 50],
        [42, 88, 27, 96, 61],
        [90, 78, 70, 86, 98]]),
 array([[42, 83, 89, 54, 57],
        [19, 93, 17, 99, 44],
        [25, 49, 14, 50, 61],
        [88, 27, 96, 61, 52],
        [78, 70, 86, 98, 89]]),
 array([[31, 77, 19, 93, 17],
        [79, 31, 25, 49, 14],
        [40, 42, 88, 27, 96],
        [49, 90, 78, 70, 86],
        [72, 97, 77, 81, 19]]),
 array([[77, 19, 93, 17, 99],
        [31, 25, 49, 14, 50],
        [42, 88, 27, 96, 61],
        [90, 78, 70, 86, 98],
        [97, 77, 81, 19,  3]]),
 array([[19, 93, 17, 99, 44],
        [25, 49, 14, 50, 61],
        [88, 27, 96, 61, 52],
        [78, 70, 86, 98, 89],
        [77, 81, 19,  3, 60]]),
 array([[79, 31, 25, 49, 14],
        [40, 42, 88, 27, 96],
        [49, 90, 78, 70, 86]

### EXERCISE 8

Write a program that delete duplicates from a NumPy array and a provided dimension (e.g., duplicate rows). Records are duplicates if all value for all other dimensions are the same. Test the programme for 2D and 3D arrays.

In [46]:
def remove_duplicates(array:np.array,dimension:int):
    removed = np.unique(array, axis = dimension).copy()
    return removed

In [48]:
data_two = np.array([
    [1, 1, 5, 8],
    [1, 1, 5, 8],
    [6, 6, 3, 4],
    [6, 6, 3, 4]
    ])

data_three = np.array([[
    [1, 1, 5, 8],
    [1, 1, 5, 8],
    [6, 6, 3, 4],
    [6, 6, 3, 4]
    ],
    [
    [1, 1, 5, 8],
    [1, 1, 5, 8],
    [6, 6, 3, 4],
    [6, 6, 3, 4]
    ]]
)


In [55]:
print("2d duplicate rows removed\n",remove_duplicates(data_two,0))
print("2d duplicate columns removed\n",remove_duplicates(data_two,1))
print("3d duplicate tables removed\n",remove_duplicates(data_three,0))
print("3d duplicate columns removed\n",remove_duplicates(data_three,1))
print("3d duplicate columns removed\n",remove_duplicates(data_three,2))


2d duplicate rows removed
 [[1 1 5 8]
 [6 6 3 4]]
2d duplicate columns removed
 [[1 5 8]
 [1 5 8]
 [6 3 4]
 [6 3 4]]
3d duplicate tables removed
 [[[1 1 5 8]
  [1 1 5 8]
  [6 6 3 4]
  [6 6 3 4]]]
3d duplicate columns removed
 [[[1 1 5 8]
  [6 6 3 4]]

 [[1 1 5 8]
  [6 6 3 4]]]
3d duplicate columns removed
 [[[1 5 8]
  [1 5 8]
  [6 3 4]
  [6 3 4]]

 [[1 5 8]
  [1 5 8]
  [6 3 4]
  [6 3 4]]]


### EXERCISE 9

Illustarate solution of 2-3 systems of linear equations from the "Mathematics for Data Analytics" course using np.linalg

In [57]:
"""
2x1 +  x2 − x3 = 0
x1  +       x3 = 4
x1  +  x2 + x3 = 0
"""
A = np.array([[2,1,-1],[1,0,1],[1,1,1]])
b = np.array([0,4,0])
x = np.linalg.solve(A,b)

print(f"Solution for {A} = {b} is {x}")

Solution for [[ 2  1 -1]
 [ 1  0  1]
 [ 1  1  1]] = [0 4 0] is [ 2.66666667 -4.          1.33333333]


### EXERCISE 10

Load numeric data from the CSV file, utilised in Lab 3 Exercise 9 into a NumPy array and calculate its statistics (by columns)

### EXERCISE 11

Using the presentations for this week and any image of your choice, illustrate
1. Loading of an image into a Numpy array
2. Flipping the image (by sorting the array)
3. Rotating the image (by transposing)
4. Filtering R,G,and B colors
5. Clipping a reactangular area the image by slicing
6. Grayscaling of the image by different colour weighting schemes - https://www.johndcook.com/blog/2009/08/24/algorithms-convert-color-grayscale/



### EXERCISE 12

Implement the following procedure for the text of "Alice in Wonderland" (see the Week 3 presentations):
1. Split the text into three pieces with similar number of words: Part1, Part2, Part3
2. For every part calculate the relative frequency of each word (number of word occurances divided by number of words in a Part)
3. Combine frequencies for all parts into NumPy array (the first dimension should correspond to the number of parts, 3)
4. Compare frequencies of word "alice" between the parts
5. Print 10 words with most significant (maximum) change of frequencies between parts
6. Print 10 words with most stable frequency (minimum) between parts

If you are interested in text analysis, read about TF-IDF - e.g., https://towardsdatascience.com/tf-idf-for-document-ranking-from-scratch-in-python-on-real-world-dataset-796d339a4089
