In [3]:
import numpy as np
# reviewing


In [75]:
A = np.array(np.arange(12))

In [76]:
A = A.reshape((3,4))
A
A.strides

(32, 8)

In [23]:
A[2,1]



9


In [38]:

# reference
B = A[1:3,:2]
# copy
C = A[1:3,:2].copy()


In [36]:
B[:,:] = 999
B.strides

(32, 8)

In [39]:
# slicing is a reference, not a copy
A

array([[  0,   1,   2,   3],
       [999, 999,   6,   7],
       [999, 999,  10,  11]])

In [42]:
C.strides

(16, 8)

In [8]:
A[1,:]

array([4, 5, 6, 7])

In [11]:

A[1,:].shape

(4,)

In [12]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
# fancy indexing
# showing 3rd row and first, then all elements
A[[2,0],:]

array([[ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

In [17]:
# showing 2nd and 3rd row, with 2nd and 3rd element
A[[2,1],1:3]

array([[ 9, 10],
       [ 5,  6]])

In [19]:
A[[True,False,True],:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [25]:
mask = A[:,3] > 5

In [26]:
A[mask,:]


array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
iris_data = np.genfromtxt('week4_files/iris.csv', delimiter=',', skip_header=1, usecols=(0,1,2,3))


In [37]:
mask = iris_data[:,0]>7
print(mask)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False  True False False  True False  True
 False  True False False False False False False False  True  True False
 False False  True False False  True False False False  True  True  True
 False False False  True False False False False False False False False
 False False False False False False]


In [38]:
iris_data[mask,:]

array([[7.1, 3. , 5.9, 2.1],
       [7.6, 3. , 6.6, 2.1],
       [7.3, 2.9, 6.3, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [7.7, 2.8, 6.7, 2. ],
       [7.2, 3.2, 6. , 1.8],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [7.7, 3. , 6.1, 2.3]])

In [40]:

A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
B = np.array(np.arange(10,22))
B = B.reshape((3,4))
B

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [45]:
# matrix addition
A + B

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [48]:
# Hadamard - product element-wise
A * B

array([[  0,  11,  24,  39],
       [ 56,  75,  96, 119],
       [144, 171, 200, 231]])

In [51]:
# T can only transpose in 2d arrays, transpose() for general
B.transpose()

array([[10, 14, 18],
       [11, 15, 19],
       [12, 16, 20],
       [13, 17, 21]])

In [55]:
# symbols for matrix multiplication
print(A @ B.T)
print(np.matmul(A,B.T))
print(np.dot(A,B.T))


[[ 74  98 122]
 [258 346 434]
 [442 594 746]]
[[ 74  98 122]
 [258 346 434]
 [442 594 746]]
[[ 74  98 122]
 [258 346 434]
 [442 594 746]]


In [58]:
D = np.array([6,1,4,4,8,4,6,3,5])
D = D.reshape((3,3))
D


array([[6, 1, 4],
       [4, 8, 4],
       [6, 3, 5]])

In [63]:
E = np.linalg.inv(D)
np.round(D @ E)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
A = np.array([[8, 3, -2], [-4, 7, 5], [3, 4, -12]])
b = np.array([9, 15, 35])
x = np.linalg.solve(A, b)
print(f"Solution:: {x}")

Solution:: [-0.58226371  3.22870478 -1.98599767]


In [72]:
print(iris_data.mean(axis=0))
print(iris_data.min(axis=0))
print(iris_data.max(axis=0))





[5.84333333 3.05733333 3.758      1.19933333]
[4.3 2.  1.  0.1]
[7.9 4.4 6.9 2.5]


In [78]:
# Broadcasting
# extends a vector/matrix dimension to make compatiable for operation to happen

A + 5


array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [80]:
A + [10,20,30,40]


array([[10, 21, 32, 43],
       [14, 25, 36, 47],
       [18, 29, 40, 51]])

In [85]:
# normalization of data by subtracting mean of data
(iris_data - iris_data.mean(axis=0))[:10]


array([[-0.74333333,  0.44266667, -2.358     , -0.99933333],
       [-0.94333333, -0.05733333, -2.358     , -0.99933333],
       [-1.14333333,  0.14266667, -2.458     , -0.99933333],
       [-1.24333333,  0.04266667, -2.258     , -0.99933333],
       [-0.84333333,  0.54266667, -2.358     , -0.99933333],
       [-0.44333333,  0.84266667, -2.058     , -0.79933333],
       [-1.24333333,  0.34266667, -2.358     , -0.89933333],
       [-0.84333333,  0.34266667, -2.258     , -0.99933333],
       [-1.44333333, -0.15733333, -2.358     , -0.99933333],
       [-0.94333333,  0.04266667, -2.258     , -1.09933333]])